"""empty message

Revision ID: 886e3c41852e
Revises: 80722126f7f1
Create Date: 2022-05-30 12:55:01.316547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886e3c41852e'
down_revision = '80722126f7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.alter_column('show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('show', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
